### ISSUE TITLE
server优雅关闭

### ISSUE THREAD

**Issue by HeyHao** [wwjwell/microboot#2]
在 demo 的 Main 类里，将 server 设为守护进程，同时也增加了同步操作，这样做的原理是什么
```   
Thread thread = new Thread(new Runnable() {
            public void run() {
                server.start();
            }
        });
        thread.setDaemon(true);
        thread.start();

synchronized (Main.class) {
            while (running) {
                try {
                    Main.class.wait();
                } catch (Throwable e) {}
            }
        }
```

**Comment by wwjwell** [comment]
守护线程，会随主进程退出而退出，如果不加同步的代码，程序刚启动就退出了。所以要加同步操作，让主线程一直存活。也可以采用System.in.read()来阻塞，让主线程一直存活。
当然也可以把线程设置为用户线程， thread.setDaemon(false)，同步的代码可以去掉。
甚至可以把thread这块代码去掉，写成
Server server = context.getBean(Server.class);
server.start(); //该方法会阻塞。
怎么样写是一个习惯问题。

demo的启动类，之所以写的这么复杂，是想给一般使用者一个参考。使程序启动代码更加规范合理。

**Comment by HeyHao** [comment]
懂了
