### ISSUE TITLE
keep alive 选项是否需要开启？

### ISSUE THREAD

**Issue by HeyHao** [wwjwell/microboot#3]
用作后端接口的 http 服务器，在接受大量短时间的请求时，keepalive 开启是不是弊大于利。
microboot 已经在你公司内部使用，开启 keepalive 是有特定场景吗？

**Comment by wwjwell** [comment]
keepalive 开启是利大于弊的，不需要特定的场景，如果你们也是用nginx做负载均衡，开启后长连接复用率是很高的。比较建议开启，tomcat也有这方面的配置，你可以百度一下。
microboot已经在我们公司内部使用，不过是我针对公司开发的定制版，有会很多内部功能。
由于能力一般，水平有限，microboot目前还有很多的缺陷可能还未被发现，可以作为学习用，但是不建议你运用到生产上。
